services:
  server:
    image: opensign/opensignserver:main
    container_name: OpenSignServer-container
    volumes:
      - opensign-files:/usr/src/app/files
    ports:
      - "8081:8080"
    # depends_on:
    #   - mongo
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST_URL:-https://open-sign.garnespratama.xyz}/app
    networks:
      - my_network
  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - my_network
  client:
    # image: opensign/opensign:main
    container_name: OpenSign-container
    build:
      context: .
      dockerfile: ./apps/OpenSign/Dockerfile
    env_file: .env.prod
    environment:
      - CHOKIDAR_USEPOLLING=true
    # Development Only
    # volumes:
    #   - ./apps/OpenSign:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - my_network
  # caddy:
  #   image: caddy:latest
  #   container_name: caddy-container
  #   ports:
  #     - "3001:3001"
  #     - "82:80"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - my_network
  #   environment:
  #     - HOST_URL=${HOST_URL:-localhost:3001}
networks:
  my_network:
    name: my_network
    driver: bridge
volumes:
  data-volume:
  web-root:
  caddy_data:
  caddy_config:
  opensign-files:
